name: Push to Azure Container Registry

on:
  workflow_dispatch:

env:
  image_name: nginx-sallam

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login ${{ vars.SERVER }} -u ${{ vars.USER_NAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push -t ${{ vars.SERVER }}/${{ env.image_name }}:latest .
