name: Push to Azure Container Registry

on:
  workflow_dispatch:

env:
  image_name: nginx-sallam

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List files in directory
        run: ls -la

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.SERVER }}/${{ vars.USER_NAME }}/${{ env.image_name }}:sallam .

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login ${{ vars.SERVER }} -u ${{ vars.USER_NAME }} --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ vars.SERVER }}/${{ vars.USER_NAME }}/${{ env.image_name }}:sallam
